export type BrushPresetKind = "brush" | "stamp";
export type BrushPresetShape = "procedural" | "mask";

export type BrushPreset = {
  id: string;
  name: string;
  group: string;
  kind: BrushPresetKind;
  shape: BrushPresetShape;
  previewSrc: string | null;
  maskSrc: string | null;
  spacing: number;
  source: string;
  sourceUrl: string | null;
};

export const DEFAULT_BRUSH_PRESET_ID = "soft-round";

export const BRUSH_PRESET_CATALOG: BrushPreset[] = [
  {
    "id": "soft-round",
    "name": "Soft Round",
    "group": "Basic",
    "kind": "brush",
    "shape": "procedural",
    "previewSrc": null,
    "maskSrc": null,
    "spacing": 0.18,
    "source": "Built-in",
    "sourceUrl": null
  },
  {
    "id": "hard-round",
    "name": "Hard Round",
    "group": "Basic",
    "kind": "brush",
    "shape": "procedural",
    "previewSrc": null,
    "maskSrc": null,
    "spacing": 0.12,
    "source": "Built-in",
    "sourceUrl": null
  },
  {
    "id": "buzz-grunge-splatter-01",
    "name": "Buzz Grunge Splatter 1",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-01-buzz-grunge-splatter-1.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-01-buzz-grunge-splatter-1.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "buzz-grunge-splatter-02",
    "name": "Buzz Grunge Splatter 2",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-02-buzz-grunge-splatter-2.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-02-buzz-grunge-splatter-2.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "buzz-grunge-splatter-03",
    "name": "Buzz Grunge Splatter 3",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-03-buzz-grunge-splatter-3.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-03-buzz-grunge-splatter-3.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "buzz-grunge-splatter-04",
    "name": "Buzz Grunge Splatter 4",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-04-buzz-grunge-splatter-4.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-04-buzz-grunge-splatter-4.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "buzz-grunge-splatter-05",
    "name": "Buzz Grunge Splatter 5",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-05-buzz-grunge-splatter-5.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-05-buzz-grunge-splatter-5.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "buzz-grunge-splatter-06",
    "name": "Buzz Grunge Splatter 6",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-06-buzz-grunge-splatter-6.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-06-buzz-grunge-splatter-6.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "buzz-grunge-splatter-07",
    "name": "Buzz Grunge Splatter 7",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-07-buzz-grunge-splatter-7.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-07-buzz-grunge-splatter-7.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "grunge-paint-01",
    "name": "Grunge Paint 5",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-paint-01-grunge-paint-5.png",
    "maskSrc": "/brush-presets/brushes/grunge-paint-01-grunge-paint-5.png",
    "spacing": 0.22,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "grunge-paint-02",
    "name": "Grunge Paint4",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-paint-02-grunge-paint4.png",
    "maskSrc": "/brush-presets/brushes/grunge-paint-02-grunge-paint4.png",
    "spacing": 0.22,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "grunge-paint-03",
    "name": "Grunge Paint 3",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-paint-03-grunge-paint-3.png",
    "maskSrc": "/brush-presets/brushes/grunge-paint-03-grunge-paint-3.png",
    "spacing": 0.22,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "grunge-paint-04",
    "name": "Grunge Paint 2",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-paint-04-grunge-paint-2.png",
    "maskSrc": "/brush-presets/brushes/grunge-paint-04-grunge-paint-2.png",
    "spacing": 0.22,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "grunge-paint-05",
    "name": "Grunge Paint 01",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-paint-05-grunge-paint-01.png",
    "maskSrc": "/brush-presets/brushes/grunge-paint-05-grunge-paint-01.png",
    "spacing": 0.22,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "smudge-01",
    "name": "Splatter Smudge 2",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smudge-01-splatter-smudge-2.png",
    "maskSrc": "/brush-presets/brushes/smudge-01-splatter-smudge-2.png",
    "spacing": 0.16,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-01",
    "name": "Water Waves 1",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-01-water-waves-1.png",
    "maskSrc": "/brush-presets/brushes/water-waves-01-water-waves-1.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-02",
    "name": "Water Waves 2",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-02-water-waves-2.png",
    "maskSrc": "/brush-presets/brushes/water-waves-02-water-waves-2.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-03",
    "name": "Water Waves 3",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-03-water-waves-3.png",
    "maskSrc": "/brush-presets/brushes/water-waves-03-water-waves-3.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-04",
    "name": "Water Waves 4",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-04-water-waves-4.png",
    "maskSrc": "/brush-presets/brushes/water-waves-04-water-waves-4.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-05",
    "name": "Water Waves 5",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-05-water-waves-5.png",
    "maskSrc": "/brush-presets/brushes/water-waves-05-water-waves-5.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-06",
    "name": "Water Waves 6",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-06-water-waves-6.png",
    "maskSrc": "/brush-presets/brushes/water-waves-06-water-waves-6.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-07",
    "name": "Water Waves 7",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-07-water-waves-7.png",
    "maskSrc": "/brush-presets/brushes/water-waves-07-water-waves-7.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-08",
    "name": "Water Waves 8",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-08-water-waves-8.png",
    "maskSrc": "/brush-presets/brushes/water-waves-08-water-waves-8.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "plant-01",
    "name": "Sampled Brush 776",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/plant-01-sampled-brush-776.png",
    "maskSrc": "/brush-presets/brushes/plant-01-sampled-brush-776.png",
    "spacing": 0.28,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-01",
    "name": "Lightning Brush 1",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/lightning-01-lightning-brush-1.png",
    "maskSrc": "/brush-presets/brushes/lightning-01-lightning-brush-1.png",
    "spacing": 0.32,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-02",
    "name": "Lightning Brush 32",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/lightning-02-lightning-brush-32.png",
    "maskSrc": "/brush-presets/brushes/lightning-02-lightning-brush-32.png",
    "spacing": 0.32,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-03",
    "name": "Lightning Brush 44",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/lightning-03-lightning-brush-44.png",
    "maskSrc": "/brush-presets/brushes/lightning-03-lightning-brush-44.png",
    "spacing": 0.32,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-04",
    "name": "Lightning Brush 1",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/lightning-04-lightning-brush-1.png",
    "maskSrc": "/brush-presets/brushes/lightning-04-lightning-brush-1.png",
    "spacing": 0.32,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-05",
    "name": "Lightning Brush 32",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/lightning-05-lightning-brush-32.png",
    "maskSrc": "/brush-presets/brushes/lightning-05-lightning-brush-32.png",
    "spacing": 0.32,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-06",
    "name": "Lightning Brush 44",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/lightning-06-lightning-brush-44.png",
    "maskSrc": "/brush-presets/brushes/lightning-06-lightning-brush-44.png",
    "spacing": 0.32,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "marble-01",
    "name": "Marble Texture 20",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-01-marble-texture-20.png",
    "maskSrc": "/brush-presets/brushes/marble-01-marble-texture-20.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-02",
    "name": "Marble Texture 18",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-02-marble-texture-18.png",
    "maskSrc": "/brush-presets/brushes/marble-02-marble-texture-18.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-03",
    "name": "Marble Texture 16",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-03-marble-texture-16.png",
    "maskSrc": "/brush-presets/brushes/marble-03-marble-texture-16.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-04",
    "name": "Marble Texture 14",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-04-marble-texture-14.png",
    "maskSrc": "/brush-presets/brushes/marble-04-marble-texture-14.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-05",
    "name": "Marble Texture 12",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-05-marble-texture-12.png",
    "maskSrc": "/brush-presets/brushes/marble-05-marble-texture-12.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-06",
    "name": "Marble Texture 9",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-06-marble-texture-9.png",
    "maskSrc": "/brush-presets/brushes/marble-06-marble-texture-9.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-07",
    "name": "Marble Texture 7",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-07-marble-texture-7.png",
    "maskSrc": "/brush-presets/brushes/marble-07-marble-texture-7.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-08",
    "name": "Marble Texture 5",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-08-marble-texture-5.png",
    "maskSrc": "/brush-presets/brushes/marble-08-marble-texture-5.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-09",
    "name": "Marble Texture 3",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-09-marble-texture-3.png",
    "maskSrc": "/brush-presets/brushes/marble-09-marble-texture-3.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-10",
    "name": "Marble Texture 1",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-10-marble-texture-1.png",
    "maskSrc": "/brush-presets/brushes/marble-10-marble-texture-1.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "travel-stamps-01",
    "name": "Sampled Brush 15",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-01-sampled-brush-15.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-01-sampled-brush-15.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-02",
    "name": "Sampled Brush 14",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-02-sampled-brush-14.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-02-sampled-brush-14.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-03",
    "name": "Sampled Brush 13",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-03-sampled-brush-13.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-03-sampled-brush-13.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-04",
    "name": "Sampled Brush 12",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-04-sampled-brush-12.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-04-sampled-brush-12.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-05",
    "name": "Sampled Brush 11",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-05-sampled-brush-11.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-05-sampled-brush-11.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-06",
    "name": "Sampled Brush 10",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-06-sampled-brush-10.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-06-sampled-brush-10.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-07",
    "name": "Sampled Brush 9",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-07-sampled-brush-9.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-07-sampled-brush-9.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-08",
    "name": "Sampled Brush 8",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-08-sampled-brush-8.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-08-sampled-brush-8.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-09",
    "name": "Sampled Brush 7",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-09-sampled-brush-7.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-09-sampled-brush-7.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-10",
    "name": "Sampled Brush 6",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-10-sampled-brush-6.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-10-sampled-brush-6.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-11",
    "name": "Sampled Brush 5",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-11-sampled-brush-5.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-11-sampled-brush-5.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-12",
    "name": "Sampled Brush 4",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-12-sampled-brush-4.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-12-sampled-brush-4.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-13",
    "name": "Sampled Brush 3",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-13-sampled-brush-3.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-13-sampled-brush-3.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-14",
    "name": "Sampled Brush 2",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-14-sampled-brush-2.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-14-sampled-brush-2.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-15",
    "name": "Sampled Brush 1",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-15-sampled-brush-1.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-15-sampled-brush-1.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-16",
    "name": "photoshopfreebrushes.com",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-16-photoshopfreebrushes-com.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-16-photoshopfreebrushes-com.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  }
];

export const BRUSH_PRESETS = BRUSH_PRESET_CATALOG.filter((preset) => preset.kind === "brush");
export const STAMP_PRESETS = BRUSH_PRESET_CATALOG.filter((preset) => preset.kind === "stamp");
