export type BrushPresetKind = "brush" | "stamp";
export type BrushPresetShape = "procedural" | "mask";

export type BrushPreset = {
  id: string;
  name: string;
  group: string;
  kind: BrushPresetKind;
  shape: BrushPresetShape;
  previewSrc: string | null;
  maskSrc: string | null;
  spacing: number;
  source: string;
  sourceUrl: string | null;
};

export const DEFAULT_BRUSH_PRESET_ID = "soft-round";

export const BRUSH_PRESET_CATALOG: BrushPreset[] = [
  {
    "id": "soft-round",
    "name": "Soft Round",
    "group": "Basic",
    "kind": "brush",
    "shape": "procedural",
    "previewSrc": null,
    "maskSrc": null,
    "spacing": 0.18,
    "source": "Built-in",
    "sourceUrl": null
  },
  {
    "id": "hard-round",
    "name": "Hard Round",
    "group": "Basic",
    "kind": "brush",
    "shape": "procedural",
    "previewSrc": null,
    "maskSrc": null,
    "spacing": 0.12,
    "source": "Built-in",
    "sourceUrl": null
  },
  {
    "id": "buzz-grunge-splatter-01",
    "name": "Buzz Grunge Splatter 1",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-01-buzz-grunge-splatter-1.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-01-buzz-grunge-splatter-1.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "buzz-grunge-splatter-02",
    "name": "Buzz Grunge Splatter 2",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-02-buzz-grunge-splatter-2.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-02-buzz-grunge-splatter-2.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "buzz-grunge-splatter-03",
    "name": "Buzz Grunge Splatter 3",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-03-buzz-grunge-splatter-3.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-03-buzz-grunge-splatter-3.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "buzz-grunge-splatter-04",
    "name": "Buzz Grunge Splatter 4",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-04-buzz-grunge-splatter-4.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-04-buzz-grunge-splatter-4.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "buzz-grunge-splatter-05",
    "name": "Buzz Grunge Splatter 5",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-05-buzz-grunge-splatter-5.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-05-buzz-grunge-splatter-5.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "buzz-grunge-splatter-06",
    "name": "Buzz Grunge Splatter 6",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-06-buzz-grunge-splatter-6.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-06-buzz-grunge-splatter-6.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "buzz-grunge-splatter-07",
    "name": "Buzz Grunge Splatter 7",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/buzz-grunge-splatter-07-buzz-grunge-splatter-7.png",
    "maskSrc": "/brush-presets/brushes/buzz-grunge-splatter-07-buzz-grunge-splatter-7.png",
    "spacing": 0.2,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "grunge-paint-01",
    "name": "Grunge Paint 5",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-paint-01-grunge-paint-5.png",
    "maskSrc": "/brush-presets/brushes/grunge-paint-01-grunge-paint-5.png",
    "spacing": 0.22,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "grunge-paint-02",
    "name": "Grunge Paint4",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-paint-02-grunge-paint4.png",
    "maskSrc": "/brush-presets/brushes/grunge-paint-02-grunge-paint4.png",
    "spacing": 0.22,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "grunge-paint-03",
    "name": "Grunge Paint 3",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-paint-03-grunge-paint-3.png",
    "maskSrc": "/brush-presets/brushes/grunge-paint-03-grunge-paint-3.png",
    "spacing": 0.22,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "grunge-paint-04",
    "name": "Grunge Paint 2",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-paint-04-grunge-paint-2.png",
    "maskSrc": "/brush-presets/brushes/grunge-paint-04-grunge-paint-2.png",
    "spacing": 0.22,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "grunge-paint-05",
    "name": "Grunge Paint 01",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-paint-05-grunge-paint-01.png",
    "maskSrc": "/brush-presets/brushes/grunge-paint-05-grunge-paint-01.png",
    "spacing": 0.22,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "grunge-titi-01",
    "name": "Titi Grunge 1",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-titi-01-titi-grunge-1.png",
    "maskSrc": "/brush-presets/brushes/grunge-titi-01-titi-grunge-1.png",
    "spacing": 0.21,
    "source": "Titi Montoya",
    "sourceUrl": null
  },
  {
    "id": "grunge-titi-02",
    "name": "Titi Grunge 2",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-titi-02-titi-grunge-2.png",
    "maskSrc": "/brush-presets/brushes/grunge-titi-02-titi-grunge-2.png",
    "spacing": 0.21,
    "source": "Titi Montoya",
    "sourceUrl": null
  },
  {
    "id": "grunge-titi-03",
    "name": "Titi Grunge 3",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-titi-03-titi-grunge-3.png",
    "maskSrc": "/brush-presets/brushes/grunge-titi-03-titi-grunge-3.png",
    "spacing": 0.21,
    "source": "Titi Montoya",
    "sourceUrl": null
  },
  {
    "id": "grunge-titi-04",
    "name": "Titi Grunge 4",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-titi-04-titi-grunge-4.png",
    "maskSrc": "/brush-presets/brushes/grunge-titi-04-titi-grunge-4.png",
    "spacing": 0.21,
    "source": "Titi Montoya",
    "sourceUrl": null
  },
  {
    "id": "grunge-titi-05",
    "name": "Titi Grunge 5",
    "group": "Grunge",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/grunge-titi-05-titi-grunge-5.png",
    "maskSrc": "/brush-presets/brushes/grunge-titi-05-titi-grunge-5.png",
    "spacing": 0.21,
    "source": "Titi Montoya",
    "sourceUrl": null
  },
  {
    "id": "smudge-01",
    "name": "Smudge",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smudge-01-smudge.png",
    "maskSrc": "/brush-presets/brushes/smudge-01-smudge.png",
    "spacing": 0.16,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "smudge-02",
    "name": "smudge",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smudge-02-smudge.png",
    "maskSrc": "/brush-presets/brushes/smudge-02-smudge.png",
    "spacing": 0.16,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "smudge-03",
    "name": "Splatter Smudge 2",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smudge-03-splatter-smudge-2.png",
    "maskSrc": "/brush-presets/brushes/smudge-03-splatter-smudge-2.png",
    "spacing": 0.16,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-01",
    "name": "Water Waves 1",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-01-water-waves-1.png",
    "maskSrc": "/brush-presets/brushes/water-waves-01-water-waves-1.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-02",
    "name": "Water Waves 2",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-02-water-waves-2.png",
    "maskSrc": "/brush-presets/brushes/water-waves-02-water-waves-2.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-03",
    "name": "Water Waves 3",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-03-water-waves-3.png",
    "maskSrc": "/brush-presets/brushes/water-waves-03-water-waves-3.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-04",
    "name": "Water Waves 4",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-04-water-waves-4.png",
    "maskSrc": "/brush-presets/brushes/water-waves-04-water-waves-4.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-05",
    "name": "Water Waves 5",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-05-water-waves-5.png",
    "maskSrc": "/brush-presets/brushes/water-waves-05-water-waves-5.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-06",
    "name": "Water Waves 6",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-06-water-waves-6.png",
    "maskSrc": "/brush-presets/brushes/water-waves-06-water-waves-6.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-07",
    "name": "Water Waves 7",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-07-water-waves-7.png",
    "maskSrc": "/brush-presets/brushes/water-waves-07-water-waves-7.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-08",
    "name": "Water Waves 8",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-08-water-waves-8.png",
    "maskSrc": "/brush-presets/brushes/water-waves-08-water-waves-8.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-09",
    "name": "Water Waves 9",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-09-water-waves-9.png",
    "maskSrc": "/brush-presets/brushes/water-waves-09-water-waves-9.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-10",
    "name": "Water Waves 10",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-10-water-waves-10.png",
    "maskSrc": "/brush-presets/brushes/water-waves-10-water-waves-10.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-11",
    "name": "Water Waves 11",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-11-water-waves-11.png",
    "maskSrc": "/brush-presets/brushes/water-waves-11-water-waves-11.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-12",
    "name": "Water Waves 12",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-12-water-waves-12.png",
    "maskSrc": "/brush-presets/brushes/water-waves-12-water-waves-12.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-13",
    "name": "Water Waves 13",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-13-water-waves-13.png",
    "maskSrc": "/brush-presets/brushes/water-waves-13-water-waves-13.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-14",
    "name": "Water Waves 14",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-14-water-waves-14.png",
    "maskSrc": "/brush-presets/brushes/water-waves-14-water-waves-14.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "water-waves-15",
    "name": "Water Waves 15",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/water-waves-15-water-waves-15.png",
    "maskSrc": "/brush-presets/brushes/water-waves-15-water-waves-15.png",
    "spacing": 0.24,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "plant-01",
    "name": "Plant 1",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/plant-01-plant-1.png",
    "maskSrc": "/brush-presets/brushes/plant-01-plant-1.png",
    "spacing": 0.28,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-01",
    "name": "Lightning Brush 1",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/lightning-01-lightning-brush-1.png",
    "maskSrc": "/brush-presets/brushes/lightning-01-lightning-brush-1.png",
    "spacing": 0.32,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-02",
    "name": "Lightning Brush 32",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/lightning-02-lightning-brush-32.png",
    "maskSrc": "/brush-presets/brushes/lightning-02-lightning-brush-32.png",
    "spacing": 0.32,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-03",
    "name": "Lightning Brush 44",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/lightning-03-lightning-brush-44.png",
    "maskSrc": "/brush-presets/brushes/lightning-03-lightning-brush-44.png",
    "spacing": 0.32,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-04",
    "name": "Demo Lightning Brushes ArtistMef CS6+ 1",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/lightning-04-demo-lightning-brushes-artistmef-cs6-1.png",
    "maskSrc": "/brush-presets/brushes/lightning-04-demo-lightning-brushes-artistmef-cs6-1.png",
    "spacing": 0.32,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-05",
    "name": "Demo Lightning Brushes ArtistMef CS6+ 2",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/lightning-05-demo-lightning-brushes-artistmef-cs6-2.png",
    "maskSrc": "/brush-presets/brushes/lightning-05-demo-lightning-brushes-artistmef-cs6-2.png",
    "spacing": 0.32,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-06",
    "name": "Demo Lightning Brushes ArtistMef CS6+ 3",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/lightning-06-demo-lightning-brushes-artistmef-cs6-3.png",
    "maskSrc": "/brush-presets/brushes/lightning-06-demo-lightning-brushes-artistmef-cs6-3.png",
    "spacing": 0.32,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-stamps-01",
    "name": "Lightning Brush 1",
    "group": "FX",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/lightning-stamps-01-lightning-brush-1.png",
    "maskSrc": "/brush-presets/stamps/lightning-stamps-01-lightning-brush-1.png",
    "spacing": 1.05,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-stamps-02",
    "name": "Lightning Brush 32",
    "group": "FX",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/lightning-stamps-02-lightning-brush-32.png",
    "maskSrc": "/brush-presets/stamps/lightning-stamps-02-lightning-brush-32.png",
    "spacing": 1.05,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-stamps-03",
    "name": "Lightning Brush 44",
    "group": "FX",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/lightning-stamps-03-lightning-brush-44.png",
    "maskSrc": "/brush-presets/stamps/lightning-stamps-03-lightning-brush-44.png",
    "spacing": 1.05,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-stamps-04",
    "name": "Demo Lightning Brushes ArtistMef CS6+ 1",
    "group": "FX",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/lightning-stamps-04-demo-lightning-brushes-artistmef-cs6-1.png",
    "maskSrc": "/brush-presets/stamps/lightning-stamps-04-demo-lightning-brushes-artistmef-cs6-1.png",
    "spacing": 1.05,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-stamps-05",
    "name": "Demo Lightning Brushes ArtistMef CS6+ 2",
    "group": "FX",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/lightning-stamps-05-demo-lightning-brushes-artistmef-cs6-2.png",
    "maskSrc": "/brush-presets/stamps/lightning-stamps-05-demo-lightning-brushes-artistmef-cs6-2.png",
    "spacing": 1.05,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "lightning-stamps-06",
    "name": "Demo Lightning Brushes ArtistMef CS6+ 3",
    "group": "FX",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/lightning-stamps-06-demo-lightning-brushes-artistmef-cs6-3.png",
    "maskSrc": "/brush-presets/stamps/lightning-stamps-06-demo-lightning-brushes-artistmef-cs6-3.png",
    "spacing": 1.05,
    "source": "Danilin",
    "sourceUrl": "https://danilin.biz/200-photoshop-brushes-free"
  },
  {
    "id": "smoke-01",
    "name": "smoke2-freegoodies-2 1",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-01-smoke2-freegoodies-2-1.png",
    "maskSrc": "/brush-presets/brushes/smoke-01-smoke2-freegoodies-2-1.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-02",
    "name": "smoke2-freegoodies-2 12",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-02-smoke2-freegoodies-2-12.png",
    "maskSrc": "/brush-presets/brushes/smoke-02-smoke2-freegoodies-2-12.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-03",
    "name": "smoke2-freegoodies-2 22",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-03-smoke2-freegoodies-2-22.png",
    "maskSrc": "/brush-presets/brushes/smoke-03-smoke2-freegoodies-2-22.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-04",
    "name": "smoke2-freegoodies-2 33",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-04-smoke2-freegoodies-2-33.png",
    "maskSrc": "/brush-presets/brushes/smoke-04-smoke2-freegoodies-2-33.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-05",
    "name": "smoke2-freegoodies-2 44",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-05-smoke2-freegoodies-2-44.png",
    "maskSrc": "/brush-presets/brushes/smoke-05-smoke2-freegoodies-2-44.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-06",
    "name": "smoke2-freegoodies-2 55",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-06-smoke2-freegoodies-2-55.png",
    "maskSrc": "/brush-presets/brushes/smoke-06-smoke2-freegoodies-2-55.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-07",
    "name": "smoke2-freegoodies-2 65",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-07-smoke2-freegoodies-2-65.png",
    "maskSrc": "/brush-presets/brushes/smoke-07-smoke2-freegoodies-2-65.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-08",
    "name": "smoke2-freegoodies-2 119",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-08-smoke2-freegoodies-2-119.png",
    "maskSrc": "/brush-presets/brushes/smoke-08-smoke2-freegoodies-2-119.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-09",
    "name": "smoke2-freegoodies-2 130",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-09-smoke2-freegoodies-2-130.png",
    "maskSrc": "/brush-presets/brushes/smoke-09-smoke2-freegoodies-2-130.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-10",
    "name": "smoke2-freegoodies-2 140",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-10-smoke2-freegoodies-2-140.png",
    "maskSrc": "/brush-presets/brushes/smoke-10-smoke2-freegoodies-2-140.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-11",
    "name": "smoke2-freegoodies-2 151",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-11-smoke2-freegoodies-2-151.png",
    "maskSrc": "/brush-presets/brushes/smoke-11-smoke2-freegoodies-2-151.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-12",
    "name": "smoke3 freegoodies 1",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-12-smoke3-freegoodies-1.png",
    "maskSrc": "/brush-presets/brushes/smoke-12-smoke3-freegoodies-1.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-13",
    "name": "smoke3 freegoodies 12",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-13-smoke3-freegoodies-12.png",
    "maskSrc": "/brush-presets/brushes/smoke-13-smoke3-freegoodies-12.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-14",
    "name": "smoke3 freegoodies 23",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-14-smoke3-freegoodies-23.png",
    "maskSrc": "/brush-presets/brushes/smoke-14-smoke3-freegoodies-23.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-15",
    "name": "smoke3 freegoodies 34",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-15-smoke3-freegoodies-34.png",
    "maskSrc": "/brush-presets/brushes/smoke-15-smoke3-freegoodies-34.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-16",
    "name": "smoke3 freegoodies 45",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-16-smoke3-freegoodies-45.png",
    "maskSrc": "/brush-presets/brushes/smoke-16-smoke3-freegoodies-45.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-17",
    "name": "smoke3 freegoodies 56",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-17-smoke3-freegoodies-56.png",
    "maskSrc": "/brush-presets/brushes/smoke-17-smoke3-freegoodies-56.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-18",
    "name": "smoke3 freegoodies 67",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-18-smoke3-freegoodies-67.png",
    "maskSrc": "/brush-presets/brushes/smoke-18-smoke3-freegoodies-67.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-19",
    "name": "smoke3 freegoodies 99",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-19-smoke3-freegoodies-99.png",
    "maskSrc": "/brush-presets/brushes/smoke-19-smoke3-freegoodies-99.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-20",
    "name": "smoke3 freegoodies 110",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-20-smoke3-freegoodies-110.png",
    "maskSrc": "/brush-presets/brushes/smoke-20-smoke3-freegoodies-110.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-21",
    "name": "smoke3 freegoodies 121",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-21-smoke3-freegoodies-121.png",
    "maskSrc": "/brush-presets/brushes/smoke-21-smoke3-freegoodies-121.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-22",
    "name": "smoke3 freegoodies 132",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-22-smoke3-freegoodies-132.png",
    "maskSrc": "/brush-presets/brushes/smoke-22-smoke3-freegoodies-132.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-23",
    "name": "smoke3 freegoodies 143",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-23-smoke3-freegoodies-143.png",
    "maskSrc": "/brush-presets/brushes/smoke-23-smoke3-freegoodies-143.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-24",
    "name": "smoke3 freegoodies 154",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-24-smoke3-freegoodies-154.png",
    "maskSrc": "/brush-presets/brushes/smoke-24-smoke3-freegoodies-154.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-25",
    "name": "smoke4 freegoodies 1",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-25-smoke4-freegoodies-1.png",
    "maskSrc": "/brush-presets/brushes/smoke-25-smoke4-freegoodies-1.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-26",
    "name": "smoke4 freegoodies 12",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-26-smoke4-freegoodies-12.png",
    "maskSrc": "/brush-presets/brushes/smoke-26-smoke4-freegoodies-12.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-27",
    "name": "smoke4 freegoodies 23",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-27-smoke4-freegoodies-23.png",
    "maskSrc": "/brush-presets/brushes/smoke-27-smoke4-freegoodies-23.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-28",
    "name": "smoke4 freegoodies 34",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-28-smoke4-freegoodies-34.png",
    "maskSrc": "/brush-presets/brushes/smoke-28-smoke4-freegoodies-34.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-29",
    "name": "smoke4 freegoodies 45",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-29-smoke4-freegoodies-45.png",
    "maskSrc": "/brush-presets/brushes/smoke-29-smoke4-freegoodies-45.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-30",
    "name": "smoke4 freegoodies 56",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-30-smoke4-freegoodies-56.png",
    "maskSrc": "/brush-presets/brushes/smoke-30-smoke4-freegoodies-56.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-31",
    "name": "smoke4 freegoodies 67",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-31-smoke4-freegoodies-67.png",
    "maskSrc": "/brush-presets/brushes/smoke-31-smoke4-freegoodies-67.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-32",
    "name": "smoke4 freegoodies 99",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-32-smoke4-freegoodies-99.png",
    "maskSrc": "/brush-presets/brushes/smoke-32-smoke4-freegoodies-99.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-33",
    "name": "smoke4 freegoodies 110",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-33-smoke4-freegoodies-110.png",
    "maskSrc": "/brush-presets/brushes/smoke-33-smoke4-freegoodies-110.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-34",
    "name": "smoke4 freegoodies 121",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-34-smoke4-freegoodies-121.png",
    "maskSrc": "/brush-presets/brushes/smoke-34-smoke4-freegoodies-121.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-35",
    "name": "smoke4 freegoodies 132",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-35-smoke4-freegoodies-132.png",
    "maskSrc": "/brush-presets/brushes/smoke-35-smoke4-freegoodies-132.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-36",
    "name": "smoke4 freegoodies 143",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-36-smoke4-freegoodies-143.png",
    "maskSrc": "/brush-presets/brushes/smoke-36-smoke4-freegoodies-143.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-37",
    "name": "smoke4 freegoodies 154",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-37-smoke4-freegoodies-154.png",
    "maskSrc": "/brush-presets/brushes/smoke-37-smoke4-freegoodies-154.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-38",
    "name": "smoke5 freegoodies 1",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-38-smoke5-freegoodies-1.png",
    "maskSrc": "/brush-presets/brushes/smoke-38-smoke5-freegoodies-1.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-39",
    "name": "smoke5 freegoodies 12",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-39-smoke5-freegoodies-12.png",
    "maskSrc": "/brush-presets/brushes/smoke-39-smoke5-freegoodies-12.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-40",
    "name": "smoke5 freegoodies 23",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-40-smoke5-freegoodies-23.png",
    "maskSrc": "/brush-presets/brushes/smoke-40-smoke5-freegoodies-23.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-41",
    "name": "smoke5 freegoodies 34",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-41-smoke5-freegoodies-34.png",
    "maskSrc": "/brush-presets/brushes/smoke-41-smoke5-freegoodies-34.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-42",
    "name": "smoke5 freegoodies 45",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-42-smoke5-freegoodies-45.png",
    "maskSrc": "/brush-presets/brushes/smoke-42-smoke5-freegoodies-45.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-43",
    "name": "smoke5 freegoodies 56",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-43-smoke5-freegoodies-56.png",
    "maskSrc": "/brush-presets/brushes/smoke-43-smoke5-freegoodies-56.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-44",
    "name": "smoke5 freegoodies 67",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-44-smoke5-freegoodies-67.png",
    "maskSrc": "/brush-presets/brushes/smoke-44-smoke5-freegoodies-67.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-45",
    "name": "smoke5 freegoodies 78",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-45-smoke5-freegoodies-78.png",
    "maskSrc": "/brush-presets/brushes/smoke-45-smoke5-freegoodies-78.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-46",
    "name": "smoke5 freegoodies 100",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-46-smoke5-freegoodies-100.png",
    "maskSrc": "/brush-presets/brushes/smoke-46-smoke5-freegoodies-100.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-47",
    "name": "smoke5 freegoodies 111",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-47-smoke5-freegoodies-111.png",
    "maskSrc": "/brush-presets/brushes/smoke-47-smoke5-freegoodies-111.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-48",
    "name": "smoke5 freegoodies 122",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-48-smoke5-freegoodies-122.png",
    "maskSrc": "/brush-presets/brushes/smoke-48-smoke5-freegoodies-122.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-49",
    "name": "smoke5 freegoodies 133",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-49-smoke5-freegoodies-133.png",
    "maskSrc": "/brush-presets/brushes/smoke-49-smoke5-freegoodies-133.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-50",
    "name": "smoke5 freegoodies 144",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-50-smoke5-freegoodies-144.png",
    "maskSrc": "/brush-presets/brushes/smoke-50-smoke5-freegoodies-144.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-51",
    "name": "smoke5 freegoodies 155",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-51-smoke5-freegoodies-155.png",
    "maskSrc": "/brush-presets/brushes/smoke-51-smoke5-freegoodies-155.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-52",
    "name": "smoke freegoodies 1",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-52-smoke-freegoodies-1.png",
    "maskSrc": "/brush-presets/brushes/smoke-52-smoke-freegoodies-1.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-53",
    "name": "smoke freegoodies 12",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-53-smoke-freegoodies-12.png",
    "maskSrc": "/brush-presets/brushes/smoke-53-smoke-freegoodies-12.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-54",
    "name": "smoke freegoodies 22",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-54-smoke-freegoodies-22.png",
    "maskSrc": "/brush-presets/brushes/smoke-54-smoke-freegoodies-22.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-55",
    "name": "smoke freegoodies 33",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-55-smoke-freegoodies-33.png",
    "maskSrc": "/brush-presets/brushes/smoke-55-smoke-freegoodies-33.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-56",
    "name": "smoke freegoodies 44",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-56-smoke-freegoodies-44.png",
    "maskSrc": "/brush-presets/brushes/smoke-56-smoke-freegoodies-44.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-57",
    "name": "smoke freegoodies 55",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-57-smoke-freegoodies-55.png",
    "maskSrc": "/brush-presets/brushes/smoke-57-smoke-freegoodies-55.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-58",
    "name": "smoke freegoodies 65",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-58-smoke-freegoodies-65.png",
    "maskSrc": "/brush-presets/brushes/smoke-58-smoke-freegoodies-65.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-59",
    "name": "smoke freegoodies 119",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-59-smoke-freegoodies-119.png",
    "maskSrc": "/brush-presets/brushes/smoke-59-smoke-freegoodies-119.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-60",
    "name": "smoke freegoodies 130",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-60-smoke-freegoodies-130.png",
    "maskSrc": "/brush-presets/brushes/smoke-60-smoke-freegoodies-130.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-61",
    "name": "smoke freegoodies 140",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-61-smoke-freegoodies-140.png",
    "maskSrc": "/brush-presets/brushes/smoke-61-smoke-freegoodies-140.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "smoke-62",
    "name": "smoke freegoodies 151",
    "group": "FX",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/smoke-62-smoke-freegoodies-151.png",
    "maskSrc": "/brush-presets/brushes/smoke-62-smoke-freegoodies-151.png",
    "spacing": 0.28,
    "source": "FreeGoodies",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-01",
    "name": "Paint Lines 1",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-01-paint-lines-1.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-01-paint-lines-1.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-02",
    "name": "Paint Lines 2",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-02-paint-lines-2.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-02-paint-lines-2.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-03",
    "name": "Paint Lines 3",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-03-paint-lines-3.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-03-paint-lines-3.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-04",
    "name": "Paint Lines 4",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-04-paint-lines-4.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-04-paint-lines-4.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-05",
    "name": "Paint Lines 5",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-05-paint-lines-5.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-05-paint-lines-5.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-06",
    "name": "Paint Lines 6",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-06-paint-lines-6.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-06-paint-lines-6.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-07",
    "name": "Paint Lines 7",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-07-paint-lines-7.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-07-paint-lines-7.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-08",
    "name": "Paint Lines 8",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-08-paint-lines-8.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-08-paint-lines-8.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-09",
    "name": "Paint Lines 9",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-09-paint-lines-9.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-09-paint-lines-9.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-10",
    "name": "Paint Lines 10",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-10-paint-lines-10.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-10-paint-lines-10.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-11",
    "name": "Paint Lines 11",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-11-paint-lines-11.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-11-paint-lines-11.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-12",
    "name": "Paint Lines 12",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-12-paint-lines-12.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-12-paint-lines-12.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-13",
    "name": "Paint Lines 13",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-13-paint-lines-13.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-13-paint-lines-13.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-14",
    "name": "Paint Lines 14",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-14-paint-lines-14.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-14-paint-lines-14.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-15",
    "name": "Paint Lines 15",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-15-paint-lines-15.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-15-paint-lines-15.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-16",
    "name": "Paint Lines 16",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-16-paint-lines-16.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-16-paint-lines-16.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-17",
    "name": "Paint Lines 17",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-17-paint-lines-17.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-17-paint-lines-17.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-18",
    "name": "Paint Lines 18",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-18-paint-lines-18.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-18-paint-lines-18.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-19",
    "name": "Paint Lines 19",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-19-paint-lines-19.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-19-paint-lines-19.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-20",
    "name": "Paint Lines 20",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-20-paint-lines-20.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-20-paint-lines-20.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-21",
    "name": "Paint Lines 21",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-21-paint-lines-21.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-21-paint-lines-21.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-22",
    "name": "Paint Lines 22",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-22-paint-lines-22.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-22-paint-lines-22.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-23",
    "name": "Paint Lines 23",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-23-paint-lines-23.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-23-paint-lines-23.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-24",
    "name": "Paint Lines 24",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-24-paint-lines-24.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-24-paint-lines-24.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "paint-lines-25",
    "name": "Paint Lines 25",
    "group": "Paint",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/paint-lines-25-paint-lines-25.png",
    "maskSrc": "/brush-presets/brushes/paint-lines-25-paint-lines-25.png",
    "spacing": 0.22,
    "source": "env1ro",
    "sourceUrl": null
  },
  {
    "id": "feathers-01",
    "name": "Feathers & Birds 1",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/feathers-01-feathers-birds-1.png",
    "maskSrc": "/brush-presets/brushes/feathers-01-feathers-birds-1.png",
    "spacing": 0.34,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feathers-02",
    "name": "Feathers & Birds 2",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/feathers-02-feathers-birds-2.png",
    "maskSrc": "/brush-presets/brushes/feathers-02-feathers-birds-2.png",
    "spacing": 0.34,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feathers-03",
    "name": "Feathers & Birds 3",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/feathers-03-feathers-birds-3.png",
    "maskSrc": "/brush-presets/brushes/feathers-03-feathers-birds-3.png",
    "spacing": 0.34,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feathers-04",
    "name": "Feathers & Birds 4",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/feathers-04-feathers-birds-4.png",
    "maskSrc": "/brush-presets/brushes/feathers-04-feathers-birds-4.png",
    "spacing": 0.34,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feathers-05",
    "name": "Feathers & Birds 5",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/feathers-05-feathers-birds-5.png",
    "maskSrc": "/brush-presets/brushes/feathers-05-feathers-birds-5.png",
    "spacing": 0.34,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feathers-06",
    "name": "Feathers & Birds 6",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/feathers-06-feathers-birds-6.png",
    "maskSrc": "/brush-presets/brushes/feathers-06-feathers-birds-6.png",
    "spacing": 0.34,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feathers-07",
    "name": "Feathers & Birds 7",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/feathers-07-feathers-birds-7.png",
    "maskSrc": "/brush-presets/brushes/feathers-07-feathers-birds-7.png",
    "spacing": 0.34,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feathers-08",
    "name": "Feathers & Birds 8",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/feathers-08-feathers-birds-8.png",
    "maskSrc": "/brush-presets/brushes/feathers-08-feathers-birds-8.png",
    "spacing": 0.34,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feathers-09",
    "name": "Feathers & Birds 9",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/feathers-09-feathers-birds-9.png",
    "maskSrc": "/brush-presets/brushes/feathers-09-feathers-birds-9.png",
    "spacing": 0.34,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feathers-10",
    "name": "Feathers & Birds 10",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/feathers-10-feathers-birds-10.png",
    "maskSrc": "/brush-presets/brushes/feathers-10-feathers-birds-10.png",
    "spacing": 0.34,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feathers-11",
    "name": "Feathers & Birds 11",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/feathers-11-feathers-birds-11.png",
    "maskSrc": "/brush-presets/brushes/feathers-11-feathers-birds-11.png",
    "spacing": 0.34,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feathers-12",
    "name": "Feathers & Birds 12",
    "group": "Nature",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/feathers-12-feathers-birds-12.png",
    "maskSrc": "/brush-presets/brushes/feathers-12-feathers-birds-12.png",
    "spacing": 0.34,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feather-stamps-01",
    "name": "Feather Stamps 1",
    "group": "Nature",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/feather-stamps-01-feather-stamps-1.png",
    "maskSrc": "/brush-presets/stamps/feather-stamps-01-feather-stamps-1.png",
    "spacing": 1.08,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feather-stamps-02",
    "name": "Feather Stamps 2",
    "group": "Nature",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/feather-stamps-02-feather-stamps-2.png",
    "maskSrc": "/brush-presets/stamps/feather-stamps-02-feather-stamps-2.png",
    "spacing": 1.08,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feather-stamps-03",
    "name": "Feather Stamps 3",
    "group": "Nature",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/feather-stamps-03-feather-stamps-3.png",
    "maskSrc": "/brush-presets/stamps/feather-stamps-03-feather-stamps-3.png",
    "spacing": 1.08,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feather-stamps-04",
    "name": "Feather Stamps 4",
    "group": "Nature",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/feather-stamps-04-feather-stamps-4.png",
    "maskSrc": "/brush-presets/stamps/feather-stamps-04-feather-stamps-4.png",
    "spacing": 1.08,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feather-stamps-05",
    "name": "Feather Stamps 5",
    "group": "Nature",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/feather-stamps-05-feather-stamps-5.png",
    "maskSrc": "/brush-presets/stamps/feather-stamps-05-feather-stamps-5.png",
    "spacing": 1.08,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feather-stamps-06",
    "name": "Feather Stamps 6",
    "group": "Nature",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/feather-stamps-06-feather-stamps-6.png",
    "maskSrc": "/brush-presets/stamps/feather-stamps-06-feather-stamps-6.png",
    "spacing": 1.08,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feather-stamps-07",
    "name": "Feather Stamps 7",
    "group": "Nature",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/feather-stamps-07-feather-stamps-7.png",
    "maskSrc": "/brush-presets/stamps/feather-stamps-07-feather-stamps-7.png",
    "spacing": 1.08,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feather-stamps-08",
    "name": "Feather Stamps 8",
    "group": "Nature",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/feather-stamps-08-feather-stamps-8.png",
    "maskSrc": "/brush-presets/stamps/feather-stamps-08-feather-stamps-8.png",
    "spacing": 1.08,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feather-stamps-09",
    "name": "Feather Stamps 9",
    "group": "Nature",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/feather-stamps-09-feather-stamps-9.png",
    "maskSrc": "/brush-presets/stamps/feather-stamps-09-feather-stamps-9.png",
    "spacing": 1.08,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feather-stamps-10",
    "name": "Feather Stamps 10",
    "group": "Nature",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/feather-stamps-10-feather-stamps-10.png",
    "maskSrc": "/brush-presets/stamps/feather-stamps-10-feather-stamps-10.png",
    "spacing": 1.08,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feather-stamps-11",
    "name": "Feather Stamps 11",
    "group": "Nature",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/feather-stamps-11-feather-stamps-11.png",
    "maskSrc": "/brush-presets/stamps/feather-stamps-11-feather-stamps-11.png",
    "spacing": 1.08,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "feather-stamps-12",
    "name": "Feather Stamps 12",
    "group": "Nature",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/feather-stamps-12-feather-stamps-12.png",
    "maskSrc": "/brush-presets/stamps/feather-stamps-12-feather-stamps-12.png",
    "spacing": 1.08,
    "source": "discopada",
    "sourceUrl": null
  },
  {
    "id": "marble-01",
    "name": "Marble Texture 20",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-01-marble-texture-20.png",
    "maskSrc": "/brush-presets/brushes/marble-01-marble-texture-20.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-02",
    "name": "Marble Texture 19",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-02-marble-texture-19.png",
    "maskSrc": "/brush-presets/brushes/marble-02-marble-texture-19.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-03",
    "name": "Marble Texture 18",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-03-marble-texture-18.png",
    "maskSrc": "/brush-presets/brushes/marble-03-marble-texture-18.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-04",
    "name": "Marble Texture 17",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-04-marble-texture-17.png",
    "maskSrc": "/brush-presets/brushes/marble-04-marble-texture-17.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-05",
    "name": "Marble Texture 16",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-05-marble-texture-16.png",
    "maskSrc": "/brush-presets/brushes/marble-05-marble-texture-16.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-06",
    "name": "Marble Texture 15",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-06-marble-texture-15.png",
    "maskSrc": "/brush-presets/brushes/marble-06-marble-texture-15.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-07",
    "name": "Marble Texture 14",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-07-marble-texture-14.png",
    "maskSrc": "/brush-presets/brushes/marble-07-marble-texture-14.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-08",
    "name": "Marble Texture 13",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-08-marble-texture-13.png",
    "maskSrc": "/brush-presets/brushes/marble-08-marble-texture-13.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-09",
    "name": "Marble Texture 12",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-09-marble-texture-12.png",
    "maskSrc": "/brush-presets/brushes/marble-09-marble-texture-12.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-10",
    "name": "Marble Texture 11",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-10-marble-texture-11.png",
    "maskSrc": "/brush-presets/brushes/marble-10-marble-texture-11.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-11",
    "name": "Marble Texture 10",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-11-marble-texture-10.png",
    "maskSrc": "/brush-presets/brushes/marble-11-marble-texture-10.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-12",
    "name": "Marble Texture 9",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-12-marble-texture-9.png",
    "maskSrc": "/brush-presets/brushes/marble-12-marble-texture-9.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-13",
    "name": "Marble Texture 8",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-13-marble-texture-8.png",
    "maskSrc": "/brush-presets/brushes/marble-13-marble-texture-8.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-14",
    "name": "Marble Texture 7",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-14-marble-texture-7.png",
    "maskSrc": "/brush-presets/brushes/marble-14-marble-texture-7.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-15",
    "name": "Marble Texture 6",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-15-marble-texture-6.png",
    "maskSrc": "/brush-presets/brushes/marble-15-marble-texture-6.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-16",
    "name": "Marble Texture 5",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-16-marble-texture-5.png",
    "maskSrc": "/brush-presets/brushes/marble-16-marble-texture-5.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-17",
    "name": "Marble Texture 4",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-17-marble-texture-4.png",
    "maskSrc": "/brush-presets/brushes/marble-17-marble-texture-4.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-18",
    "name": "Marble Texture 3",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-18-marble-texture-3.png",
    "maskSrc": "/brush-presets/brushes/marble-18-marble-texture-3.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-19",
    "name": "Marble Texture 2",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-19-marble-texture-2.png",
    "maskSrc": "/brush-presets/brushes/marble-19-marble-texture-2.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "marble-20",
    "name": "Marble Texture 1",
    "group": "Texture",
    "kind": "brush",
    "shape": "mask",
    "previewSrc": "/brush-presets/brushes/marble-20-marble-texture-1.png",
    "maskSrc": "/brush-presets/brushes/marble-20-marble-texture-1.png",
    "spacing": 0.24,
    "source": "Videoinfographica",
    "sourceUrl": "https://videoinfographica.com/ph-brushes/"
  },
  {
    "id": "travel-stamps-01",
    "name": "Travel Stamps 1",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-01-travel-stamps-1.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-01-travel-stamps-1.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-02",
    "name": "Travel Stamps 2",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-02-travel-stamps-2.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-02-travel-stamps-2.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-03",
    "name": "Travel Stamps 3",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-03-travel-stamps-3.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-03-travel-stamps-3.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-04",
    "name": "Travel Stamps 4",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-04-travel-stamps-4.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-04-travel-stamps-4.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-05",
    "name": "Travel Stamps 5",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-05-travel-stamps-5.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-05-travel-stamps-5.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-06",
    "name": "Travel Stamps 6",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-06-travel-stamps-6.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-06-travel-stamps-6.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-07",
    "name": "Travel Stamps 7",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-07-travel-stamps-7.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-07-travel-stamps-7.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-08",
    "name": "Travel Stamps 8",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-08-travel-stamps-8.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-08-travel-stamps-8.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-09",
    "name": "Travel Stamps 9",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-09-travel-stamps-9.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-09-travel-stamps-9.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-10",
    "name": "Travel Stamps 10",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-10-travel-stamps-10.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-10-travel-stamps-10.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-11",
    "name": "Travel Stamps 11",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-11-travel-stamps-11.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-11-travel-stamps-11.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-12",
    "name": "Travel Stamps 12",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-12-travel-stamps-12.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-12-travel-stamps-12.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-13",
    "name": "Travel Stamps 13",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-13-travel-stamps-13.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-13-travel-stamps-13.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-14",
    "name": "Travel Stamps 14",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-14-travel-stamps-14.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-14-travel-stamps-14.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-15",
    "name": "Travel Stamps 15",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-15-travel-stamps-15.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-15-travel-stamps-15.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "travel-stamps-16",
    "name": "Travel Stamps 16",
    "group": "Travel",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/travel-stamps-16-travel-stamps-16.png",
    "maskSrc": "/brush-presets/stamps/travel-stamps-16-travel-stamps-16.png",
    "spacing": 1.1,
    "source": "Creativo",
    "sourceUrl": "https://creativo.one/adds/brushes/21754-kisti-dlya-fotoshopa-shtampyi.html"
  },
  {
    "id": "rubber-stamps-01",
    "name": "Rubber Stamps 1",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-01-rubber-stamps-1.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-01-rubber-stamps-1.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  },
  {
    "id": "rubber-stamps-02",
    "name": "Rubber Stamps 2",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-02-rubber-stamps-2.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-02-rubber-stamps-2.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  },
  {
    "id": "rubber-stamps-03",
    "name": "Rubber Stamps 3",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-03-rubber-stamps-3.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-03-rubber-stamps-3.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  },
  {
    "id": "rubber-stamps-04",
    "name": "Rubber Stamps 4",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-04-rubber-stamps-4.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-04-rubber-stamps-4.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  },
  {
    "id": "rubber-stamps-05",
    "name": "Rubber Stamps 5",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-05-rubber-stamps-5.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-05-rubber-stamps-5.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  },
  {
    "id": "rubber-stamps-06",
    "name": "Rubber Stamps 6",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-06-rubber-stamps-6.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-06-rubber-stamps-6.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  },
  {
    "id": "rubber-stamps-07",
    "name": "Rubber Stamps 7",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-07-rubber-stamps-7.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-07-rubber-stamps-7.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  },
  {
    "id": "rubber-stamps-08",
    "name": "Rubber Stamps 8",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-08-rubber-stamps-8.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-08-rubber-stamps-8.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  },
  {
    "id": "rubber-stamps-09",
    "name": "Rubber Stamps 9",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-09-rubber-stamps-9.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-09-rubber-stamps-9.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  },
  {
    "id": "rubber-stamps-10",
    "name": "Rubber Stamps 10",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-10-rubber-stamps-10.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-10-rubber-stamps-10.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  },
  {
    "id": "rubber-stamps-11",
    "name": "Rubber Stamps 11",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-11-rubber-stamps-11.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-11-rubber-stamps-11.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  },
  {
    "id": "rubber-stamps-12",
    "name": "Rubber Stamps 12",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-12-rubber-stamps-12.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-12-rubber-stamps-12.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  },
  {
    "id": "rubber-stamps-13",
    "name": "Rubber Stamps 13",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-13-rubber-stamps-13.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-13-rubber-stamps-13.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  },
  {
    "id": "rubber-stamps-14",
    "name": "Rubber Stamps 14",
    "group": "Stamp",
    "kind": "stamp",
    "shape": "mask",
    "previewSrc": "/brush-presets/stamps/rubber-stamps-14-rubber-stamps-14.png",
    "maskSrc": "/brush-presets/stamps/rubber-stamps-14-rubber-stamps-14.png",
    "spacing": 1.12,
    "source": "Photoshop Supply",
    "sourceUrl": "https://www.photoshopsupply.com/brushes/stamp-photoshop-brushes"
  }
];

export const BRUSH_PRESETS = BRUSH_PRESET_CATALOG.filter((preset) => preset.kind === "brush");
export const STAMP_PRESETS = BRUSH_PRESET_CATALOG.filter((preset) => preset.kind === "stamp");
